### ISSUE TITLE
Commands resulting in non-expected output

### ISSUE THREAD

**Issue by GHOSTL0V3** [Daste745/nagatoro#6]
When certain commands are called ;balance and ;warns results in a non-expected result. See screenshot for example 

[Example Here](https://cdn.discordapp.com/attachments/832766537688809512/835710769144397844/nagatoro_bot_error.png)

**Comment by Daste745** [comment]
Thanks for bringing this up. Looks like I forgot to use the correct localization key for the "This user has no warns" message - working on a fix right now. 
Do you have any more examples of this happening? Manually reviewing all my code for these i18n bugs would take too much time.

**Comment by Daste745** [comment]
Resolved in ed427d3619fb9e3cc10e8cfef2ec946c32ffd68d. If you have any other examples of this bug, please reopen the issue and post them here.
